* intro
Tools to understand neural representations. 

I'll use org files as the default enhanced text file format. 

* dir
I try to be very organized. As much as possible, files are organized in
an if-then-else fashion. What this means is that if directories form a
decision tree on the space of all files, then the subdirectories of a
given one are ordered. Their descriptions (the region of space they
occupy) are not necessarily non-intersecting. It should be understood
that the *first* matching subdirectory will be where the file is placed.

The root directory encompasses the entire space. Thus, all files are
allowed to be placed there (and many miscellaneous ones are). 

** main.py
Script to execute. i.e ./main.py ...

Name may change (Fri Jun 14 15:20:45 EDT 2019)
** misc.org
Default case for relevant information. Contains the weekly updates.
** analysis
Data analysis. The results that will be presented. 

analysis-n is typically the analysis notebook for the results
generated by slurm/mk_resultsn.
** hnb
"Helper notebook." Files in this directory are to
- help me code
- help the reader understand
the resulting .py files.

These are basically files that contain an exact copy of the function,
just with loops denested (run once with an arbitrary value, to help
debugging) and structure broken down.

Temporary files needed by hnb's are also here. 
** tests
Testing correctness of code for bugs. Includes slurm scripts, notebooks
that load in generated results (to see if the generated results work). 
** slurm
SLURM scripts, as well as additional files to aid the scripts. 

Scripts here are run directly as ~SCRIPTNAME~. They typically contain 
